#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/forest/launch.sh &

# 单屏幕
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 1 2 3 4 5 6 7 8 9 0
# 双屏幕
bspc monitor "HDMI-1" -d I II III IV V VI VII VIII IX
bspc monitor "eDP-1" -d X
# 三屏幕
#bspc monitor "HDMI-1" -d I II III IV V
#bspc monitor "eDP-1" -d VI VII VIII 
#bspc monitor "DP-2" -d IX X 

bspc config border_width        2
bspc config window_gap          12
bspc config top_padding         35

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
